### ISSUE TITLE
Add all of reducers to `Reducible.prototype`

### ISSUE THREAD

**Issue by Raynos** [Gozala/reducible#1]
``` js
Reducible.prototype.map = function () {
  return map(this, ...arguments)
}
```

Would allow us to do 

``` js
map(someReducible, function() {

}).
map(function () {
 ...
}).
map(function () {
  ...
})
```

Which would make the API surface nicer and less lispy and more array like.

**Comment by Gozala** [comment]
No that direction is very limiting and usually means everything should come with library or it's a second class function. I do think that sugar for skipping intermediate results is out of this library scope.

There are bunch of dsl libraries though that solve just that specific problem via underscore like [chaining](http://underscorejs.org/#chain) or [fab](https://github.com/Gozala/synthesize) like currying.

Also note that not everything inherits from `Reducible` and adding such constraint is not worth it.

**Comment by Gozala** [comment]
Feel free to make other library though that combines dsl + reducers + all the other utilities, and call it **hoarders-reduce** or something.

**Comment by Raynos** [comment]
@Gozala I could add `"reducers/map"` to `Object.prototype`!
